name: CI Linux

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug]
    name: 'build-linux [${{ matrix.configuration}}]'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install libs
      run: sudo apt update && sudo apt install meson libstdc++-10-dev libvulkan-dev glslang-tools libsdl2-dev libgl-dev libegl-dev
    - name: Install Conan
      run: pip install conan
    - name: Configure with cmake
      run: |
        export CC=clang-11
        export CXX=clang++-11
        ${CXX} --version
        mkdir build && cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    - name: Build dependencies
      run: ninja dependencies
      working-directory: build
    - name: Build project
      run: ninja
      working-directory: build
