name: CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug, msvc-release]#, clang-debug]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: storm-engine.${{ matrix.configuration }}
        path: build\${{ matrix.configuration }}\bin
    - name: Run tests
      run: '${{ github.workspace }}/build/${{ matrix.configuration }}/bin/test-all.exe'
