name: CI Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '*.md'

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug, msvc-release]
        enable_steam: [false]
        include:
          - enable_steam: true
            configuration: msvc-release
    name: 'build-windows [${{ matrix.configuration}}, steam: ${{ matrix.enable_steam }}]'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
        cmakeAppendedArgs: '-DSTORM_ENABLE_STEAM=${{ matrix.enable_steam }} -DSTORM_ENABLE_CRASH_REPORTS=ON'
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: storm-engine.${{ matrix.configuration }}-steam-${{ matrix.enable_steam}}
        path: build\${{ matrix.configuration }}\bin
